=sumifs(Vishal!H:H,Vishal!C:C,C3)
=sumifs(Harish!H:H,Harish!C:C,C3)
=sumifs(Shashi!H:H,Shashi!C:C,C3)
=sumifs(Samuel!H:H,Samuel!C:C,C3)
=sumifs(Satish!H:H,Satish!C:C,C3)
=sumifs(Nandu!H:H,Nandu!C:C,C3)
=sumifs(Rahul!H:H,Rahul!C:C,C3)
=sumifs(Sourab!H:H,Sourab!C:C,C3)

=sumifs(Anita!H:H,Anita!C:C,C3)
=sumifs(Soumya!H:H,Soumya!C:C,C3)
=sumifs(Pradip!H:H,Pradip!C:C,C3)
=sumifs(Ujwal!H:H,Ujwal!C:C,C3)
=sumifs(Naveen!H:H,Naveen!C:C,C3)
=sumifs(Renuka!H:H,Renuka!C:C,C3)
=sumifs(Aditya!H:H,Aditya!C:C,C3)
=sumifs(Himabindu!H:H,Himabindu!C:C,C3)
